version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ota-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL:-https://api.devnet.solana.com}
      - SOLANA_PROGRAM_ID=${SOLANA_PROGRAM_ID}
      - SOLANA_NETWORK=${SOLANA_NETWORK:-devnet}
      - SOLANA_ADMIN_KEYPAIR=${SOLANA_ADMIN_KEYPAIR:-/app/secrets/admin-keypair.json}
      - TREASURY_ADDRESS=${TREASURY_ADDRESS}
      - OPINION_TRADING_PROGRAM_ID=${OPINION_TRADING_PROGRAM_ID}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - CLIENT_URL=${CLIENT_URL:-http://localhost:3000}
    volumes:
      - ./admin-keypair.json:/app/secrets/admin-keypair.json:ro
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ota-network

networks:
  ota-network:
    driver: bridge
